package clienterror

import (
	"fmt"
	"strings"
)

const (
	LocalPrefix       = "【sub2freeApi限制】"
	legacyLocalPrefix = "【" + "本" + "项目限制】"
	UpstreamPrefix    = "【上游错误】"
)

func Prefix(errType, message string) string {
	if IsUpstream(errType, message) {
		return Upstream(message)
	}
	return Local(message)
}

func Local(message string) string {
	if !brandedErrors {
		return withoutKnownPrefix(message)
	}
	return withPrefix(LocalPrefix, message)
}

func Upstream(message string) string {
	if !brandedErrors {
		return withoutKnownPrefix(message)
	}
	return withPrefix(UpstreamPrefix, message)
}

func IsUpstream(errType, message string) bool {
	errType = strings.TrimSpace(strings.ToLower(errType))
	if strings.Contains(errType, "upstream") || errType == "overloaded_error" {
		return true
	}
	msg := strings.TrimSpace(strings.ToLower(message))
	return strings.HasPrefix(msg, "upstream ") ||
		strings.HasPrefix(msg, "upstream:") ||
		strings.Contains(msg, " upstream ") ||
		strings.Contains(msg, "upstream request") ||
		strings.Contains(msg, "upstream service")
}

func withPrefix(prefix, message string) string {
	message = strings.TrimSpace(message)
	if prefix == LocalPrefix && strings.HasPrefix(message, legacyLocalPrefix) {
		message = strings.TrimSpace(strings.TrimPrefix(message, legacyLocalPrefix))
	}
	if hasKnownPrefix(message) {
		return message
	}
	if message == "" {
		return prefix
	}
	return prefix + " " + message
}

func hasKnownPrefix(message string) bool {
	return strings.HasPrefix(message, LocalPrefix) || strings.HasPrefix(message, UpstreamPrefix)
}

func withoutKnownPrefix(message string) string {
	message = strings.TrimSpace(message)
	for _, prefix := range []string{LocalPrefix, legacyLocalPrefix, UpstreamPrefix} {
		if strings.HasPrefix(message, prefix) {
			return strings.TrimSpace(strings.TrimPrefix(message, prefix))
		}
	}
	return message
}

// Source identifies errors generated by this gateway before they reach clients.
var Source = "sub2api"

var sourceMarker = "source: " + Source
var sourceSuffix = " (" + sourceMarker + ")"
var brandedErrors bool
var sourceSuffixEnabled bool

// Configure selects the immutable client-visible error policy for this process.
// It must be called once after configuration validation and before serving requests.
func Configure(profile string) error {
	switch strings.ToLower(strings.TrimSpace(profile)) {
	case "", "main":
		Source = "sub2api"
		brandedErrors = false
		sourceSuffixEnabled = false
	case "free":
		Source = "sub2freeApi"
		brandedErrors = true
		sourceSuffixEnabled = true
	default:
		return fmt.Errorf("unsupported deployment profile %q", profile)
	}
	sourceMarker = "source: " + Source
	sourceSuffix = " (" + sourceMarker + ")"
	return nil
}

// WithSource makes project-generated client-visible error messages self-attributing.
func WithSource(message string) string {
	message = strings.TrimSpace(message)
	if !sourceSuffixEnabled {
		return message
	}
	if message == "" {
		return sourceMarker
	}
	if strings.Contains(strings.ToLower(message), strings.ToLower(sourceMarker)) {
		return message
	}
	return message + sourceSuffix
}
