package clienterr

import "strings"

const (
	// Source identifies errors generated by this gateway before they reach clients.
	Source = "sub2api"

	sourceMarker = "source: " + Source
	sourceSuffix = " (" + sourceMarker + ")"
)

// WithSource makes project-generated client-visible error messages self-attributing.
func WithSource(message string) string {
	message = strings.TrimSpace(message)
	if message == "" {
		return sourceMarker
	}
	if strings.Contains(strings.ToLower(message), sourceMarker) {
		return message
	}
	return message + sourceSuffix
}
